steps:
  - name: "gcr.io/dataform-public/dataform-builder"
    args:
      ["build", "-t", "gcr.io/dataform-public/dataform-builder", "-f", "cloudbuild/Dockerfile", "."]
  - name:
    args: ["./cloudbuild/run_tests.sh"]
